version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    env_file:
      - .env
    container_name: sqlserver
    ports:
      - "1433:1433"
    volumes:
      - astest_data:/var/opt/mssql/data
    restart: unless-stopped

  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: AutoSpaceTestTask.Web/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db

volumes:
  astest_data: